name: Cron Test Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  

jobs:
  cron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
        pre-release-dependencies: ["--pre", ""]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install uv (Unix)
      if: runner.os != 'Windows'
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      run: powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install base dependencies
      run: |
        uv pip install wheel --system
        uv pip install ${{ matrix.pre-release-dependencies }} --system -e ".[test-dep]"
        uv pip freeze
    - name: Test base
      run: |
        pytest -n auto --disable-warnings --cov=sklego -m "not cvxpy and not formulaic and not umap"

    - name: Install cvxpy dependencies
      run: |
        uv pip install ${{ matrix.pre-release-dependencies }} --system -e ".[cvxpy]"
        uv pip freeze
    - name: Test cvxpy
      run: pytest -n auto --disable-warnings --cov=sklego -m cvxpy

    - name: Install formulaic dependencies
      run: |
        uv pip install ${{ matrix.pre-release-dependencies }} --system -e ".[formulaic]"
        uv pip freeze
    - name: Test with pytest
      run: pytest -n auto --disable-warnings --cov=sklego -m formulaic
    
    - name: Install umap dependencies
      run: |
        uv pip install ${{ matrix.pre-release-dependencies }} --system -e ".[umap]"
        uv pip freeze
    - name: Test with pytest
      run: pytest -n auto --disable-warnings --cov=sklego -m umap
