name: Cron Test Dependencies

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
        pre-release-dependencies: ["--pre", ""]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install uv
      run: |
         if ['${{ runner.os }}' == 'Windows']; then
            powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
         else
            curl -LsSf https://astral.sh/uv/install.sh | sh
         fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv pip install wheel --system
        uv pip install ${{ matrix.pre-release-dependencies }} scikit-lego --system
        uv pip freeze
    - name: Test with pytest
      run: |
        uv pip install -e ".[test]"
        make test
